name: Publish Changed Packages

on:
  push:
    branches:
      - 'dev'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if changeset exists
        id: changeset_check
        run: |
          if ls .changeset/*.md > /dev/null 2>&1; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
            echo "No changeset found â€” skipping workflow."
          fi

      - name: Setup pnpm
        if: steps.changeset_check.outputs.found == 'true'
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        if: steps.changeset_check.outputs.found == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Update npm to latest version
        if: steps.changeset_check.outputs.found == 'true'
        run: npm install -g npm@latest

      - name: Install dependencies
        if: steps.changeset_check.outputs.found == 'true'
        run: pnpm install --frozen-lockfile

      - name: Build only changed packages
        if: steps.changeset_check.outputs.found == 'true'
        run: pnpm turbo run build --filter=...[HEAD^1]

      - name: Create release version
        if: steps.changeset_check.outputs.found == 'true'
        run: pnpm changeset version

      - name: Git commit & push
        if: steps.changeset_check.outputs.found == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ðŸš€ version changed packages" || echo "No changes to commit"
          git push origin dev

      - name: Publish packages
        if: steps.changeset_check.outputs.found == 'true'
        run: pnpm changeset publish
