name: Publish Changed Packages

on:
  push:
    branches:
      - 'main'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check changeset file
        id: check
        run: |
          if ls .changeset/*.md > /dev/null 2>&1; then
            echo "hasChangesets=true" >> $GITHUB_OUTPUT
            echo "Changeset found â€” running workflow."
          else
            echo "hasChangesets=false" >> $GITHUB_OUTPUT
            echo "No changeset found â€” skipping workflow."
          fi
    outputs:
      hasChangesets: ${{ steps.check.outputs.hasChangesets }}
  release:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.hasChangesets == 'true'
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm release:install

      - name: Build packages
        run: pnpm release:build

      - name: Create release version
        run: pnpm changeset version

      - name: Git commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ðŸš€ version changed packages" || echo "No changes to commit"
          git push origin HEAD:main --follow-tags

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish packages
        id: publish
        run: |
          pnpm release > release.log 2>&1 || true
          cat release.log
          echo "log<<EOF" >> $GITHUB_OUTPUT
          cat release.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true

      - name: Slack notification
        run: pnpm release:notify
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          LOG: ${{ steps.publish.outputs.log }}
