name: Publish Changed Packages

on:
  push:
    branches:
      - 'dev'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Check changeset file
      #   id: changesets
      #   run: |
      #     if ls .changeset/*.md > /dev/null 2>&1; then
      #       echo "hasChangesets=true" >> $GITHUB_OUTPUT
      #       echo "Changeset found â€” running workflow."
      #     else
      #       echo "hasChangesets=false" >> $GITHUB_OUTPUT
      #       echo "No changeset found â€” skipping workflow."
      #     fi

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        # if: steps.changesets.outputs.hasChangesets == 'true'
        run: pnpm install --frozen-lockfile

      # - name: Build only changed packages
      #   if: steps.changesets.outputs.hasChangesets == 'true'
      #   run: pnpm changeset:build

      # - name: Create release version
      #   if: steps.changesets.outputs.hasChangesets == 'true'
      #   run: pnpm changeset version

      - name: Create release version
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'ðŸš€ version changed packages'
          createPullRequest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Git commit & push
      #   if: steps.changesets.outputs.hasChangesets == 'true'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "ðŸš€ version changed packages" || echo "No changes to commit"
      #     git push origin HEAD:dev --follow-tags

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish packages
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: pnpm release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
